/**
 * LPで使う写真。表示時にDBを叩かないよう、モブの旅の写真から抜いて固定してある。
 * 幅はWikimediaで実際に配信されるものだけを採用（全数 HTTP 200 を確認済み）。
 */
export interface LpPhoto { src: string; title: string; pref: string }

export const LP_PHOTOS: LpPhoto[] = [
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Senkoji_Onomichi16s3872.jpg/960px-Senkoji_Onomichi16s3872.jpg', title: 'Senko-ji', pref: 'Hiroshima' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/230728_Chusonji_Hiraizumi_Iwate_pref_Japan01s3.jpg/960px-230728_Chusonji_Hiraizumi_Iwate_pref_Japan01s3.jpg', title: 'Chuson-ji', pref: 'Iwate' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Ritsurin.JPG/960px-Ritsurin.JPG', title: 'Ritsurin Garden', pref: 'Kagawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sakurajima55.jpg/960px-Sakurajima55.jpg', title: 'Sakurajima', pref: 'Kagoshima' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Kumamoto_Castle_Keep_Tower_20221022-3.jpg/960px-Kumamoto_Castle_Keep_Tower_20221022-3.jpg', title: 'Kumamoto Castle', pref: 'Kumamoto' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Fushimiinari-taisha%2C_gehaiden-1.jpg/960px-Fushimiinari-taisha%2C_gehaiden-1.jpg', title: 'Fushimi Inari', pref: 'Kyoto' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/D%C5%8Dgo_Onsen.jpg/960px-D%C5%8Dgo_Onsen.jpg', title: 'Dogo Onsen', pref: 'Ehime' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Risshaku-ji_konponchudo.jpg/960px-Risshaku-ji_konponchudo.jpg', title: 'Yamadera', pref: 'Yamagata' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Beppu_Tower02s4s3200.jpg/960px-Beppu_Tower02s4s3200.jpg', title: 'Beppu Hells', pref: 'Oita' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Yamazakimisaki.jpg/960px-Yamazakimisaki.jpg', title: 'Kushiro Marsh', pref: 'Hokkaido' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Nagasaki_glover_16835805_886671322b_o_d.jpg', title: 'Glover Garden', pref: 'Nagasaki' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/20200119_Sapporo_Clock_Tower.jpg/960px-20200119_Sapporo_Clock_Tower.jpg', title: 'Sapporo Clock Tower', pref: 'Hokkaido' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Naha_Okinawa_Japan_Shuri-Castle-01.jpg/960px-Naha_Okinawa_Japan_Shuri-Castle-01.jpg', title: 'Shuri Castle', pref: 'Okinawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Yufuin_Onsen_-Mus%C5%8Den_02.jpg/960px-Yufuin_Onsen_-Mus%C5%8Den_02.jpg', title: 'Yufuin', pref: 'Oita' },
  { src: 'https://upload.wikimedia.org/wikipedia/ja/thumb/7/79/Kochi_Katsurahama_Daytime_2.JPG/960px-Kochi_Katsurahama_Daytime_2.JPG', title: 'Katsurahama', pref: 'Kochi' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Suwako2.jpg', title: 'Lake Suwa', pref: 'Nagano' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Lake_Ashi_Aerial_photograph.1976.jpg/960px-Lake_Ashi_Aerial_photograph.1976.jpg', title: 'Lake Ashi', pref: 'Kanagawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Hakodate_Goryokaku_Panorama_1.JPG/960px-Hakodate_Goryokaku_Panorama_1.JPG', title: 'Goryokaku', pref: 'Hokkaido' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Hirosaki-castle_Aomori_with_Sakura_blossoms.jpg', title: 'Hirosaki Castle', pref: 'Aomori' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Izumo-taisha14bs4592.jpg/960px-Izumo-taisha14bs4592.jpg', title: 'Izumo Taisha', pref: 'Shimane' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/%E7%A7%8B%E3%81%AE%E4%B8%8A%E9%AB%98%E5%9C%B0_%28Kamikochi_in_autumn%29_24_Oct%2C_2011_-_panoramio.jpg', title: 'Kamikochi', pref: 'Nagano' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Lake_Tazawa_and_Kansa-g%C5%AB_20210213.jpg/960px-Lake_Tazawa_and_Kansa-g%C5%AB_20210213.jpg', title: 'Lake Tazawa', pref: 'Akita' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Sign_of_Farm_Tomita.jpg', title: 'Farm Tomita', pref: 'Hokkaido' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shirakawa-go_%282017-07-22%29.jpg/960px-Shirakawa-go_%282017-07-22%29.jpg', title: 'Shirakawa-go', pref: 'Gifu' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Genbaku_Dome04-r.JPG/960px-Genbaku_Dome04-r.JPG', title: 'Hiroshima Peace Park', pref: 'Hiroshima' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Zenkoji_Temple_Hondo.jpg/960px-Zenkoji_Temple_Hondo.jpg', title: 'Zenko-ji', pref: 'Nagano' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Takayama_Jinya_Entrance_201706.jpg/960px-Takayama_Jinya_Entrance_201706.jpg', title: 'Takayama Jinya', pref: 'Gifu' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Matsumoto_Castle_1-1.jpg/960px-Matsumoto_Castle_1-1.jpg', title: 'Matsumoto Castle', pref: 'Nagano' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Kabira-Bay-Kabira-park-2019.jpg/960px-Kabira-Bay-Kabira-park-2019.jpg', title: 'Kabira Bay', pref: 'Okinawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Kenrokuen10-r.jpg/960px-Kenrokuen10-r.jpg', title: 'Kenroku-en', pref: 'Ishikawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Kurasiki_morning01.JPG/960px-Kurasiki_morning01.JPG', title: 'Kurashiki Canal', pref: 'Okayama' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Kotohira-gu01s.jpg/960px-Kotohira-gu01s.jpg', title: 'Konpira-san', pref: 'Kagawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/20100719_Dazaifu_Tenmangu_Shrine_3328.jpg/960px-20100719_Dazaifu_Tenmangu_Shrine_3328.jpg', title: 'Dazaifu Tenmangu', pref: 'Fukuoka' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/%E6%9D%B1%E5%A4%A7%E5%AF%BA_%E5%A4%A7%E4%BB%8F%E6%AE%BF%EF%BC%882024%E5%B9%B4%EF%BC%89.jpg/960px-%E6%9D%B1%E5%A4%A7%E5%AF%BA_%E5%A4%A7%E4%BB%8F%E6%AE%BF%EF%BC%882024%E5%B9%B4%EF%BC%89.jpg', title: 'Todai-ji', pref: 'Nara' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Matsue_Castle_Keep_Tower_20230617.jpg/960px-Matsue_Castle_Keep_Tower_20230617.jpg', title: 'Matsue Castle', pref: 'Shimane' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Osaka_Dotonbori_Ebisu_Bridge.jpg/960px-Osaka_Dotonbori_Ebisu_Bridge.jpg', title: 'Dotonbori', pref: 'Osaka' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Tokyo-STA_Marunouchi-Entrance_2023.jpg/960px-Tokyo-STA_Marunouchi-Entrance_2023.jpg', title: 'Tokyo Station', pref: 'Tokyo' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sensoji_2023.jpg/960px-Sensoji_2023.jpg', title: 'Senso-ji', pref: 'Tokyo' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kinkaku-ji_2015.JPG/960px-Kinkaku-ji_2015.JPG', title: 'Kinkaku-ji', pref: 'Kyoto' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Takachiho-kyo%28Gorge%29_-_River_-_%E5%B7%9D.jpg/960px-Takachiho-kyo%28Gorge%29_-_River_-_%E5%B7%9D.jpg', title: 'Takachiho Gorge', pref: 'Miyazaki' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Onna_Okinawa_Japan_Cape-Manzamo-01.jpg/960px-Onna_Okinawa_Japan_Cape-Manzamo-01.jpg', title: 'Cape Manzamo', pref: 'Okinawa' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/SendaiJoOtemonSumiYagura2003-11.jpg', title: 'Sendai Castle', pref: 'Miyagi' },
  { src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Himeji_castle_in_may_2015.jpg/960px-Himeji_castle_in_may_2015.jpg', title: 'Himeji Castle', pref: 'Hyogo' },
];
