/**
 * 診断結果に出す、都道府県ごとの紹介文（47件×5言語）。
 *
 * 「山・街・自然」のようなタグの羅列では土地の顔が見えない（ユーザー指摘）ので、
 * どんな場所か・何があるか・何ができるか・いつが良いか・何が旨いか、を
 * 4〜5文の散文で持つ。**文はここに直書きする** ―― i18n.ts の辞書に混ぜると
 * 47×5=235キーで辞書が読めなくなるため、このファイルだけで完結させる。
 *
 * 書き換えるときの決まり
 *  - 観光地・料理は実在の固有名詞で。ふわっとした形容だけの文にしない
 *  - 5言語すべて同時に直す（どれかだけ直すと言語で内容がズレる）
 */
import type { Locale } from '@/lib/i18n';

const JA: Record<number, string> = {
  1: '雄大な自然と食の宝庫、北海道。夏は富良野のラベンダー畑と美瑛の丘、冬はさっぽろ雪まつりと世界屈指のパウダースノーが待っています。知床では野生動物に出会い、函館では夜景と朝市を。海鮮丼、ジンギスカン、味噌ラーメンと、食だけでも旅の理由になる土地です。',
  2: 'ねぶた祭と津軽三味線の県、青森。奥入瀬渓流の遊歩道、十和田湖、そして日本屈指の桜の名所・弘前城。八甲田の樹氷や酸ヶ湯温泉など、雪の季節も濃厚です。大間のマグロと嶽きみ、りんごのスイーツも忘れずに。春の桜と8月のねぶたが特におすすめです。',
  3: '平泉の中尊寺金色堂を擁する、歴史と山の県・岩手。浄土ヶ浜の白い岩と青い海、龍泉洞の地底湖、遠野の民話の里と、静かな見どころが点在します。わんこそば・盛岡冷麺・じゃじゃ麺の「盛岡三大麺」に挑むのも一興。混雑と無縁のまま東北の深部を味わえます。新緑と紅葉の季節が狙い目です。',
  4: '杜の都・仙台を中心に、海と山がそろう宮城。日本三景・松島の島めぐり、伊達政宗の城下町散歩、蔵王の御釜と見どころが続きます。夏の仙台七夕まつりも有名。牛タンにずんだ餅、三陸の寿司と食も強力です。街の便利さと自然を1泊圏内で行き来できるのが魅力です。',
  5: '乳頭温泉郷の秘湯と、なまはげの里・秋田。日本一深い田沢湖、武家屋敷の残る角館、冬の横手かまくらと、雪国の情緒が詰まっています。きりたんぽ鍋と稲庭うどん、日本酒も粒ぞろい。桜と新緑の角館、雪見露天の冬、どちらも絵になります。人の少ない静かな旅がしたい人にこそ。',
  6: '山寺（立石寺）の石段と、蔵王の樹氷の県・山形。銀山温泉の大正ロマンの街並みは、雪の夜がいちばん美しい。夏はさくらんぼ狩り、秋は芋煮会と、季節の楽しみがはっきりしています。米沢牛と冷やしラーメンも名物。温泉と雪景色を静かに味わう旅に向いています。',
  7: '会津の城下町と磐梯山の県、福島。鶴ヶ城と武家屋敷、宿場町の面影が残る大内宿、五色沼の青いカルデラ湖群が見どころです。喜多方ラーメンの朝ラー文化、円盤餃子、馬刺しと食も渋い。冬の雪見と、裏磐梯の紅葉が特に見事です。東京から近いのに驚くほど静かです。',
  8: '春のネモフィラと秋のコキアで知られる、ひたち海浜公園の県・茨城。日本三名園の偕楽園、袋田の滝、牛久大仏と見どころは骨太です。太平洋のアンコウ鍋と常陸牛、納豆も本場。花の見頃（4〜5月・10月）に合わせると、丘一面が青や紅に染まる絶景に会えます。',
  9: '日光東照宮の豪華絢爛と、中禅寺湖・華厳の滝の自然が同居する栃木。鬼怒川温泉でゆっくり温まり、宇都宮で餃子をはしごするのが定番です。あしかがフラワーパークの大藤（4月末〜5月）とイルミネーションも有名。世界遺産と温泉を一度に楽しむなら、まずこの県です。',
  10: '草津・伊香保・四万と、名湯がひしめく温泉県・群馬。草津の湯畑が硫黄の湯気を上げ、石段街の伊香保では射的と温泉まんじゅうを。世界遺産の富岡製糸場、谷川岳のロープウェイも見どころです。水沢うどんと焼きまんじゅうが名物。雪見露天の冬と、新緑の初夏がおすすめです。',
  11: '小江戸・川越の蔵造りの町並みが看板の埼玉。氷川神社の縁結び風鈴、長瀞のライン下り、秩父の芝桜と、日帰り圏に見どころが揃います。12月の秩父夜祭は日本三大曳山祭のひとつ。うなぎと武蔵野うどんも名物です。東京から30分で「江戸」に会える手軽さが魅力です。',
  12: '成田山新勝寺の門前町と、九十九里の海の県・千葉。銚子の犬吠埼灯台では本州でいちばん早い初日の出を拝めます。養老渓谷のハイキング、鴨川や勝浦の海の幸も魅力。金目鯛の煮付けと勝浦タンタンメンが名物です。東京の隣で、漁師町の空気と灯台の風景に会えます。',
  13: '世界最大級の都市でありながら、路地に入れば下町が残る東京。浅草寺と仲見世、明治神宮の森、渋谷のスクランブル交差点と、新旧の顔が数駅ごとに切り替わります。寿司・ラーメン・天ぷら、ミシュランの星の数は世界一。美術館も夜の街も、深さは底なしです。何度来ても「初めての東京」が見つかります。',
  14: '横浜の港町、鎌倉の古都、箱根の温泉と、三つの顔を持つ神奈川。鎌倉の大仏と江ノ電の車窓、箱根の芦ノ湖と大涌谷、横浜中華街の食べ歩きが定番です。芦ノ湖越しの富士山は晴れた冬がいちばんきれい。東京から1時間で、海も山も温泉もそろいます。',
  15: '米と酒の国、新潟。日本酒の蔵は約90と全国最多で、駅ナカの「ぽんしゅ館」では利き酒が楽しめます。夏は佐渡島の美しい海とたらい舟、冬は苗場や湯沢の上質な雪。へぎそばとのどぐろ、栃尾の油揚げも名物です。8月の長岡花火は一生ものの迫力です。',
  16: '立山黒部アルペンルートの「雪の大谷」で知られる富山。標高3,000m級の山々と富山湾が近く、雨晴海岸からは海越しの立山連峰が望めます。富山湾の白えび・ホタルイカ・寒ブリは鮮度が別格。世界一美しいスタバと呼ばれる環水公園も人気です。雪の壁は4〜6月だけの絶景です。',
  17: '金沢の兼六園と茶屋街を擁する、工芸と美食の県・石川。ひがし茶屋街で金箔ソフトを片手に歩き、21世紀美術館で現代アートを。輪島塗や九谷焼など伝統工芸の体験も豊富です。近江町市場の海鮮丼とのどぐろは必食。雪吊りの兼六園が見られる冬も風情があります。',
  18: '東尋坊の断崖と、恐竜王国・福井。福井県立恐竜博物館は世界三大恐竜博物館のひとつで、子ども連れに絶大な人気です。曹洞宗大本山の永平寺では静寂の朝課を見学できます。越前がに（冬）とおろしそば、ソースカツ丼が名物。観光客が少なく、静かな北陸を独り占めできます。',
  19: '富士山を最も美しく望む県、山梨。河口湖の湖面に映る逆さ富士、新倉山浅間公園の五重塔と富士のセットは世界的に有名です。ぶどうとワインの勝沼、ほうとう鍋、桃狩りと食も充実。富士五湖でのキャンプやサウナも人気です。空気の澄む晩秋〜冬が、富士山のベストシーズンです。',
  20: '3,000m級の峰が連なる、山の王国・長野。上高地の梓川と穂高連峰、地獄谷の温泉に浸かるスノーモンキー、松本城と善光寺と、見どころが尽きません。夏は避暑とトレッキング、冬は白馬・野沢のスキーと雪見温泉。信州そばと野沢菜、りんごも名物です。山が好きなら、まずここです。',
  21: '白川郷の合掌造りと、城下町・飛騨高山の県・岐阜。古い町並みで飛騨牛の握りを頬張り、朝市を冷やかすのが定番です。下呂温泉は日本三名泉のひとつ。長良川の鵜飼（5〜10月）は1,300年続く夏の風物詩です。雪をかぶった白川郷のライトアップは、冬だけのご褒美です。',
  22: '富士山と駿河湾に挟まれた、お茶とわさびの県・静岡。三保松原から望む富士、日本平の茶畑、伊豆の温泉と海岸線が見どころです。駿河湾の桜えびとしらす、うなぎ、静岡おでんと食も豊か。熱海や修善寺は東京から新幹線ですぐ。富士山を眺めながらの露天風呂は格別です。',
  23: '名古屋めしの本場、愛知。味噌カツ・ひつまぶし・手羽先・モーニング文化と、食の個性は全国屈指です。金鯱の名古屋城、徳川美術館、ジブリパークと見どころも多彩。三河湾の離島・佐久島はアートの島として人気上昇中です。街歩きと食い倒れを軸にした旅が似合います。',
  24: '伊勢神宮の県、三重。日本人の「一生に一度はお伊勢参り」の目的地で、おかげ横丁の食べ歩きも楽しみのうちです。夫婦岩の日の出、海女文化の残る鳥羽・志摩、リアス海岸の英虞湾も見どころ。松阪牛と伊勢えび、てこね寿司と食も一級品。凛とした冬の早朝参拝が特に清々しいです。',
  25: '日本一の湖・琵琶湖を抱く滋賀。湖に鳥居が浮かぶ白鬚神社、国宝・彦根城、比叡山延暦寺と、水と歴史の見どころが並びます。近江牛は日本最古のブランド和牛。湖畔のサイクリングロード「ビワイチ」は自転車乗りの聖地です。京都からわずか10分で、この静けさに出会えます。',
  26: '千年の都、京都。伏見稲荷の千本鳥居、金閣寺、清水の舞台と、名所を挙げればきりがありません。桜と紅葉の美しさは別格ですが、その分この時期は混みます。朝の竹林や夜の先斗町など、時間帯をずらすのが上級者の歩き方。湯豆腐から懐石、抹茶スイーツまで、食も雅です。',
  27: '「食い倒れ」の街、大阪。道頓堀のネオンとグリコ看板、たこ焼き・お好み焼き・串カツのはしごが王道です。大阪城、通天閣、ユニバーサル・スタジオ・ジャパンと遊び場も揃っています。人懐っこい街の空気は日本随一。夜が長い旅、笑いと食の旅がしたいならここです。',
  28: '白鷺城と呼ばれる世界遺産・姫路城の県、兵庫。異国情緒の残る神戸の街、六甲山からの1,000万ドルの夜景、城崎温泉の外湯めぐりと、顔ぶれが多彩です。神戸牛と明石焼き、灘の酒も外せません。有馬温泉は豊臣秀吉も愛した日本最古級の名湯。街・城・温泉を一度に楽しめます。',
  29: '大仏と鹿の古都、奈良。東大寺の大仏殿、鹿がお辞儀する奈良公園、朱塗りの春日大社が定番です。少し足を延ばせば、山全体が桜に染まる吉野山（4月）や、日本最古の道・山の辺の道も。柿の葉寿司と葛餅が名物です。京都より人が少なく、より古い日本に会えます。',
  30: '熊野古道と高野山、祈りの県・和歌山。杉木立の参道を歩き、宿坊に泊まって精進料理と朝のお勤めを体験できます。那智の滝と熊野那智大社の朱塗りの対比は息をのむ美しさ。白浜の砂浜とパンダ、勝浦のマグロも魅力です。歩く旅・整う旅がしたい人に向いています。',
  31: '日本最大級の砂の海、鳥取砂丘の県。砂丘ではラクダ遊覧やサンドボードが楽しめ、隣の砂の美術館では砂像アートが見られます。『ゲゲゲの鬼太郎』の水木しげるロード、白壁土蔵の倉吉も見どころ。冬の松葉ガニと二十世紀梨が名物です。人の少なさは全国屈指 ―― それが贅沢です。',
  32: '縁結びの神様・出雲大社の県、島根。神々が集うとされる社に参り、宍道湖の夕日を眺めるのが王道です。世界遺産の石見銀山、堀川めぐりの松江城、庭園日本一の足立美術館と、渋い見どころが揃います。出雲そばとしじみ汁が名物。神在月（旧暦10月）の参拝は格別です。',
  33: '「晴れの国」岡山。白壁とやなぎの倉敷美観地区、日本三名園の後楽園と烏城（岡山城）が看板です。瀬戸内に浮かぶ犬島・豊島へのアートの旅の玄関口でもあります。白桃とマスカット、ばら寿司と果物王国の名に恥じない食も魅力。雨が少なく、一年を通して外れの少ない旅先です。',
  34: '原爆ドームと厳島神社、二つの世界遺産を持つ広島。海に浮かぶ宮島の大鳥居は、満潮と干潮で別の顔を見せます。お好み焼きと牡蠣、尾道ラーメンと食も強豪揃い。しまなみ海道のサイクリングは瀬戸内の多島美を体で感じられます。歴史に向き合い、海に癒される旅ができます。',
  35: '本州最西端の山口。錦帯橋の五連アーチ、CNNが「日本の最も美しい場所」に選んだ元乃隅神社の赤い鳥居の列、秋吉台のカルスト台地と、写真映えする風景が続きます。下関のふぐは本場中の本場。萩の城下町では幕末の志士の足跡をたどれます。静かで濃い、通好みの県です。',
  36: '阿波おどりと鳴門の渦潮の県、徳島。8月の阿波おどりは街全体が踊り場になります。祖谷のかずら橋と深い渓谷は日本三大秘境のひとつ。鳴門海峡の渦潮は船からもガラス床の遊歩道からも見られます。徳島ラーメンとすだち、鳴門鯛が名物。夏の祭りと秘境歩きが両輪です。',
  37: '「うどん県」香川。朝から製麺所をはしごする讃岐うどん巡礼が名物です。瀬戸内国際芸術祭の直島・豊島はアートの聖地として世界に知られています。ミシュラン三つ星の栗林公園、こんぴらさんの785段の石段も見どころ。日本一小さい県に、食とアートがぎゅっと詰まっています。',
  38: '道後温泉の県、愛媛。『千と千尋』のモデルとも言われる道後温泉本館で湯に浸かり、浴衣で商店街を歩くのが定番です。現存12天守の松山城、しまなみ海道の島々、宇和海の段々畑も見どころ。鯛めしとみかんは本場の味。文学の街・松山で、司馬遼太郎や正岡子規の足跡もたどれます。',
  39: '最後の清流・四万十川の県、高知。沈下橋を自転車で渡り、カヌーで川を下る旅ができます。よさこい祭り（8月）と日曜市、桂浜の坂本龍馬像も定番。カツオの藁焼きたたきは、香りから別物です。柏島の海の透明度は沖縄級。豪快な食と川遊びの、夏がいちばん似合う県です。',
  40: '屋台の街、福岡。中洲の川沿いに並ぶ屋台で、豚骨ラーメンと焼きラーメンをはしごする夜が名物です。太宰府天満宮の梅、糸島の海辺のカフェ、柳川の川下りと日帰り圏も充実。もつ鍋・明太子・うどんと、食の層の厚さは九州随一。空港から市内まで地下鉄で5分という近さも魅力です。',
  41: '有田焼・伊万里焼のふるさと、佐賀。窯元の町を歩き、ろくろ体験や器の買い付けが楽しめます。呼子の朝市では透きとおるイカの活造りを。祐徳稲荷神社の懸崖造りと、秋のバルーンフェスタ（11月）も見どころです。嬉野・武雄の温泉も名湯揃い。器と食を愛する人の県です。',
  42: '坂と教会の港町、長崎。グラバー園と大浦天主堂、稲佐山からの世界新三大夜景が定番です。軍艦島クルーズでは廃墟の島に上陸できます。ちゃんぽん・皿うどん・カステラと、鎖国時代の唯一の窓口らしい和華蘭グルメも魅力。路面電車でめぐる異国情緒は、日本の他のどこにもありません。',
  43: '阿蘇の大カルデラと熊本城の県、熊本。世界最大級のカルデラを馬が駆ける草千里、雲海の大観峰と、スケールの大きい風景が続きます。復旧の進む熊本城、水の澄んだ白川水源も見どころ。馬刺しとあか牛丼、辛子蓮根が名物です。黒川温泉の露天めぐりを足せば、自然・城・湯が一度に揃います。',
  44: '源泉数・湧出量ともに日本一の「おんせん県」大分。別府では地獄めぐりと砂湯、由布院では金鱗湖の朝霧と洗練された温泉街を楽しめます。とり天と関あじ・関さば、だんご汁が名物。湯布院の紅葉と雪見露天の冬が特に風情があります。温泉が旅の目的なら、ここが本丸です。',
  45: '神話と南国の県、宮崎。天孫降臨の地・高千穂峡でボートを漕ぎ、真名井の滝を見上げる体験は唯一無二です。鬼の洗濯板が広がる青島、都井岬の野生馬、日南海岸のドライブも爽快。チキン南蛮と地鶏の炭火焼、マンゴーが名物です。冬でも温暖で、一年中サーフィンができます。',
  46: '桜島が煙を上げる薩摩の国、鹿児島。錦江湾越しの活火山を眺めながら、天然の砂むし温泉（指宿）に埋まる体験はここだけです。世界遺産・屋久島の縄文杉、奄美の海まで、圏内の自然は桁違い。黒豚しゃぶしゃぶと薩摩揚げ、芋焼酎が名物。維新の歴史も濃く、見応えの尽きない県です。',
  47: '琉球王国の面影と、世界屈指の海の県・沖縄。首里城と斎場御嶽で琉球の祈りに触れ、慶良間や宮古・石垣の海でシュノーケルとダイビングを。沖縄そばとゴーヤーチャンプルー、泡盛と食文化も独自です。海のベストは5〜10月ですが、冬でも20度前後と温暖。日本の中のもうひとつの国です。',
};

const EN: Record<number, string> = {
  1: 'Hokkaido is Japan\'s great northern wilderness — and its pantry. Summer brings the lavender fields of Furano and the hills of Biei; winter means the Sapporo Snow Festival and some of the world\'s best powder snow. Spot wild animals in Shiretoko, then hit Hakodate for its night view and morning market. Seafood bowls, jingisukan lamb BBQ and miso ramen are reasons to visit on their own.',
  2: 'Aomori is the land of the Nebuta Festival and Tsugaru shamisen. Walk the Oirase Gorge trail, cruise Lake Towada, and see Hirosaki Castle — one of Japan\'s finest cherry-blossom spots. Winter is just as rich, with the snow monsters of Hakkoda and the Sukayu hot spring. Don\'t miss Oma tuna and apple sweets. Best in cherry season and during August\'s Nebuta.',
  3: 'Iwate is quiet history country, home to the golden hall of Chuson-ji in Hiraizumi. The white cliffs of Jodogahama, the underground lake of Ryusendo cave and the folklore village of Tono dot the prefecture. Try the "three great noodles" of Morioka — wanko soba, reimen and jajamen. Deep Tohoku, without the crowds. Aim for fresh green or autumn-leaf season.',
  4: 'Miyagi pairs the "city of trees" Sendai with sea and mountains. Cruise the pine islands of Matsushima — one of Japan\'s three great views — stroll the castle town of the samurai lord Date Masamune, and peer into the crater lake of Zao. August brings the famous Tanabata festival. Gyutan (beef tongue), zunda mochi and Sanriku sushi are the local table.',
  5: 'Akita is the land of hidden hot springs — Nyuto Onsen above all — and the Namahage demons. Japan\'s deepest lake Tazawa, the samurai street of Kakunodate and the snow huts of Yokote pack it with snow-country charm. Kiritanpo hotpot, Inaniwa udon and superb sake round it out. Beautiful under Kakunodate\'s cherry blossoms, and in open-air baths in the snow.',
  6: 'Yamagata means the 1,000 stone steps of Yamadera temple and the snow monsters of Zao. The gaslit streets of Ginzan Onsen are at their most beautiful on a snowy night. Summer is cherry-picking season; autumn brings imoni stew parties on the riverbanks. Yonezawa beef and chilled ramen are the local specialities. A prefecture for quiet hot springs and snow scenery.',
  7: 'Fukushima is castle-town Aizu and the Bandai highlands. See Tsuruga Castle and samurai residences, the Edo-period post town of Ouchi-juku, and the blue volcanic ponds of Goshiki-numa. Kitakata is famous for morning ramen; try the enban gyoza too. Superb autumn leaves in Urabandai and atmospheric snow in winter. Surprisingly quiet for somewhere so close to Tokyo.',
  8: 'Ibaraki is home to Hitachi Seaside Park, where whole hills turn blue with nemophila in spring and red with kochia in autumn. Kairakuen — one of Japan\'s three great gardens — Fukuroda Falls and the giant Ushiku Buddha anchor the sights. From the Pacific come anglerfish hotpot and Hitachi beef; this is also natto\'s homeland. Time your visit for the flowers (April–May, October).',
  9: 'Tochigi holds the gilded splendour of Nikko Toshogu beside the natural beauty of Lake Chuzenji and Kegon Falls. Soak in Kinugawa Onsen, then hop between gyoza shops in Utsunomiya. Ashikaga Flower Park is famous for its great wisteria (late April–May) and winter illuminations. For a World Heritage site and hot springs in one trip, start here.',
  10: 'Gunma is hot-spring country: Kusatsu, Ikaho and Shima. Watch sulphurous steam rise from Kusatsu\'s yubatake, then climb Ikaho\'s stone steps with an onsen manju in hand. The World Heritage Tomioka Silk Mill and the Tanigawadake ropeway round out the sights. Mizusawa udon and yaki-manju are the local bites. Best in snow season or fresh early summer.',
  11: 'Saitama\'s calling card is Kawagoe, "Little Edo", with its clay-walled warehouse streets. Add the wind chimes of Hikawa Shrine, boat rides down the Nagatoro rapids and the pink moss fields of Chichibu. The Chichibu Night Festival in December is one of Japan\'s three great float festivals. Eel and Musashino udon are the specialities — and Edo is only 30 minutes from Tokyo.',
  12: 'Chiba is the temple town of Naritasan Shinsho-ji and the long Kujukuri coast. At Cape Inubosaki lighthouse you can catch Honshu\'s earliest sunrise. Hike Yoro Gorge, then eat your way through the fishing ports of Kamogawa and Katsuura. Simmered kinmedai (golden-eye snapper) and Katsuura tantanmen are the dishes to order. Fishing-town air, right next to Tokyo.',
  13: 'Tokyo is one of the world\'s great megacities — yet old shitamachi lanes survive a few blocks from the neon. Senso-ji and its Nakamise arcade, the forest of Meiji Shrine and the Shibuya scramble crossing swap eras every few train stops. It has more Michelin stars than any city on earth: sushi, ramen, tempura. However many times you come, there is always a first-time Tokyo waiting.',
  14: 'Kanagawa wears three faces: the port city of Yokohama, the old capital of Kamakura and the hot springs of Hakone. See the Great Buddha and ride the Enoden line along the sea, cruise Lake Ashi past Owakudani\'s volcanic steam, then graze through Yokohama\'s Chinatown. Mt Fuji over Lake Ashi is sharpest on clear winter days. Sea, mountains and onsen, one hour from Tokyo.',
  15: 'Niigata is Japan\'s rice-and-sake heartland, with about 90 breweries — the most of any prefecture — and a tasting hall right inside the station. Summer means Sado Island\'s clear water and tub-boat rides; winter means superb snow at Naeba and Yuzawa. Hegi soba, nodoguro rosy seabass and Tochio\'s giant fried tofu are the local table. The Nagaoka fireworks in August are once-in-a-lifetime.',
  16: 'Toyama is famous for the "snow corridor" of the Tateyama Kurobe Alpine Route, its walls of snow open April–June. Three-thousand-metre peaks rise straight from the bay, and from Amaharashi Coast you can see them across the water. Toyama Bay\'s white shrimp, firefly squid and winter yellowtail are exceptionally fresh. Kansui Park, home of "the world\'s most beautiful Starbucks", is a favourite too.',
  17: 'Ishikawa is Kanazawa: Kenrokuen garden, geisha teahouse districts and a deep craft tradition. Stroll Higashi Chaya with gold-leaf ice cream, then take in the 21st Century Museum of Contemporary Art. Try your hand at Wajima lacquer or Kutani porcelain. The seafood bowls and nodoguro of Omicho market are essential eating. Winter, when Kenrokuen wears its snow ropes, is quietly beautiful.',
  18: 'Fukui means the sheer cliffs of Tojinbo and dinosaurs — its Dinosaur Museum ranks among the world\'s three best and is a hit with families. At Eihei-ji, the head temple of Soto Zen, you can watch the silent morning service. Echizen crab (winter), grated-daikon soba and sauce katsudon are the dishes. Few tourists come — which means the quiet Hokuriku coast is all yours.',
  19: 'Yamanashi owns the classic views of Mt Fuji: the reflection on Lake Kawaguchi and the five-storey pagoda of Arakurayama Sengen Park. Katsunuma is Japan\'s wine country, and houtou noodle hotpot and peach picking fill out the menu. Camping and sauna culture thrive around the Fuji Five Lakes. Late autumn to winter, when the air is clearest, is Fuji\'s best season.',
  20: 'Nagano is Japan\'s mountain kingdom, ringed by 3,000-metre peaks. Walk the Azusa River at Kamikochi, watch snow monkeys soak in hot springs at Jigokudani, and visit Matsumoto Castle and Zenko-ji temple. Summer is for trekking and cool air; winter for Hakuba and Nozawa\'s slopes and snowy open-air baths. Shinshu soba, nozawana pickles and apples are the staples. If you love mountains, start here.',
  21: 'Gifu holds the thatched villages of Shirakawa-go and the castle town of Hida Takayama. Graze on Hida beef sushi in the old streets, then browse the morning market. Gero is one of Japan\'s three famous hot springs, and cormorant fishing on the Nagara River (May–October) is a 1,300-year-old summer rite. The snowy light-up of Shirakawa-go is a winter-only reward.',
  22: 'Shizuoka sits between Mt Fuji and Suruga Bay — tea and wasabi country. See Fuji from the pine grove of Miho no Matsubara, walk tea fields at Nihondaira, and follow the Izu coast from onsen to onsen. Sakura shrimp, shirasu, eel and Shizuoka oden fill the table. Atami and Shuzenji are a short shinkansen hop from Tokyo. An open-air bath with Fuji in view is hard to beat.',
  23: 'Aichi is the home of "Nagoya meshi": miso katsu, hitsumabushi eel, chicken wings and a famous breakfast culture. Nagoya Castle with its golden dolphins, the Tokugawa Art Museum and Ghibli Park lead the sights. The little art island of Sakushima in Mikawa Bay is quietly gaining fans. A city-walking, eat-everything kind of trip suits it best.',
  24: 'Mie is the prefecture of Ise Jingu, the destination of the classic once-in-a-lifetime pilgrimage — with the food stalls of Okage Yokocho as part of the fun. See sunrise between the wedded rocks of Meoto Iwa, meet the ama divers of Toba and Shima, and cruise Ago Bay\'s ria coast. Matsusaka beef, spiny lobster and tekone sushi are first-rate. A crisp winter-morning visit to the shrine is unforgettable.',
  25: 'Shiga wraps around Lake Biwa, Japan\'s largest lake. A torii gate floats offshore at Shirahige Shrine; national-treasure Hikone Castle and the monastery of Mt Hiei watch over the water. Omi beef is Japan\'s oldest wagyu brand. Cyclists come from all over for the "Biwaichi" loop around the lake. All this calm is just ten minutes by train from Kyoto.',
  26: 'Kyoto was Japan\'s capital for a thousand years. The vermilion tunnel of Fushimi Inari, the gold of Kinkaku-ji, the stage of Kiyomizu — the list of famous sights never ends. Cherry blossom and autumn leaves are peerless here, and peak crowds come with them; go early to the bamboo grove or late to Pontocho like a local. From yudofu to kaiseki to matcha sweets, even the food is elegant.',
  27: 'Osaka is Japan\'s eating capital. Under the neon of Dotonbori and the Glico sign, hop from takoyaki to okonomiyaki to kushikatsu. Osaka Castle, Tsutenkaku tower and Universal Studios Japan cover the daytime. The city\'s friendly, talkative streak is unmatched in Japan. Come here for long nights, laughter and food.',
  28: 'Hyogo is home to Himeji Castle, the White Heron — a World Heritage site. Add the cosmopolitan streets of Kobe, the "ten-million-dollar" night view from Mt Rokko and the seven public baths of Kinosaki Onsen. Kobe beef, akashiyaki and Nada sake are essential. Arima Onsen, beloved by the shogun Hideyoshi, is among Japan\'s oldest springs. City, castle and onsen in one trip.',
  29: 'Nara is the old capital of the Great Buddha and the bowing deer. Todai-ji\'s vast Buddha hall, deer-filled Nara Park and the vermilion Kasuga Taisha make the classic circuit. Go further for Yoshino, a whole mountain of cherry blossoms in April, or the ancient Yamanobe road. Persimmon-leaf sushi and kudzu sweets are the local taste. Fewer crowds than Kyoto — and an older Japan.',
  30: 'Wakayama is pilgrimage country: the Kumano Kodo trails and the monastery mountain of Koyasan. Walk cedar-lined paths, sleep in temple lodgings and join the morning prayers. The sight of Nachi Falls beside the vermilion pagoda is breathtaking. Shirahama\'s white beach and pandas, and Katsuura\'s tuna, round it out. For walkers and soul-restorers.',
  31: 'Tottori has Japan\'s largest sand dunes — ride a camel, try sandboarding, then see the carved masterpieces of the Sand Museum. The yokai bronze statues of Mizuki Shigeru Road and the white-walled storehouses of Kurayoshi add character. Winter matsuba crab and 20th-century pears are the tastes. It is one of Japan\'s least-crowded prefectures — and that is the luxury.',
  32: 'Shimane is home to Izumo Taisha, the grand shrine of matchmaking where the gods of Japan are said to gather. Watch the sunset over Lake Shinji, tour the World Heritage Iwami Ginzan silver mine, and see Japan\'s finest garden at the Adachi Museum. Izumo soba and shijimi clam soup are the staples. Visiting in Kamiarizuki — the month the gods arrive — is special.',
  33: 'Okayama, the "Land of Sunshine", is the white walls and willows of the Kurashiki Bikan quarter, plus Korakuen — one of Japan\'s three great gardens — and Crow Castle. It is also the gateway to the art islands of Inujima and Teshima. White peaches, muscat grapes and barazushi live up to the fruit-kingdom name. With little rain year-round, it rarely disappoints.',
  34: 'Hiroshima holds two World Heritage sites: the A-Bomb Dome and Itsukushima Shrine. Miyajima\'s great torii shows a different face at high and low tide. Okonomiyaki, oysters and Onomichi ramen make it a food heavyweight too. Cycling the Shimanami Kaido puts the island-dotted Inland Sea under your own two wheels. A trip that faces history and is healed by the sea.',
  35: 'Yamaguchi, at Honshu\'s western tip, is a run of photogenic landscapes: the five arches of Kintaikyo bridge, the red torii rows of Motonosumi Shrine — picked by CNN among Japan\'s most beautiful places — and the karst plateau of Akiyoshidai. Shimonoseki is the true home of fugu. In Hagi\'s castle town you can trace the footsteps of the Meiji Restoration. Quiet, deep and for connoisseurs.',
  36: 'Tokushima is the Awa Odori and the Naruto whirlpools. In August the whole city becomes a dance floor. The vine bridges and deep gorges of the Iya Valley rank among Japan\'s three hidden regions. See the whirlpools from a boat or the glass-floored walkway. Tokushima ramen, sudachi citrus and Naruto sea bream feed you well. Summer festival plus secret valleys — that\'s the pairing.',
  37: 'Kagawa is the "Udon Prefecture" — pilgrims hop between noodle mills from breakfast. Naoshima and Teshima, stages of the Setouchi Triennale, are world-famous art islands. Ritsurin Garden holds three Michelin stars, and Konpira-san\'s 785 stone steps are a rite of passage. Japan\'s smallest prefecture, packed tight with food and art.',
  38: 'Ehime means Dogo Onsen, said to have inspired Spirited Away — bathe in the grand old bathhouse, then stroll the arcades in a yukata. Matsuyama Castle is one of only twelve original keeps; the Shimanami islands and the terraced shores of the Uwa Sea lie beyond. Tai-meshi sea bream rice and mikan are the true local taste. A literary city too, from Soseki to Shiki.',
  39: 'Kochi is the Shimanto, Japan\'s "last clear stream" — cycle over its low-water bridges and canoe its length. The Yosakoi festival in August, the Sunday market and Sakamoto Ryoma\'s statue at Katsurahama fill out the classics. Straw-seared katsuo tataki is a different dish here — the aroma alone. Kashiwajima\'s water rivals Okinawa\'s. A summer prefecture of big food and river play.',
  40: 'Fukuoka is the city of yatai — riverside food stalls in Nakasu where you hop from tonkotsu ramen to yaki-ramen late into the night. Day trips are rich too: the plum groves of Dazaifu Tenmangu, seaside cafés in Itoshima, canal boats in Yanagawa. Motsunabe, mentaiko and udon give it Kyushu\'s deepest food bench. The airport is five minutes from downtown by subway.',
  41: 'Saga is the birthplace of Arita and Imari porcelain — walk the kiln towns, throw a pot, and shop for tableware. At Yobuko\'s morning market the squid sashimi is served still translucent. The cliff-hung Yutoku Inari Shrine and November\'s international balloon festival are the other draws. Ureshino and Takeo are fine hot springs too. A prefecture for people who love ceramics and food.',
  42: 'Nagasaki is a port city of slopes and churches. Glover Garden, Oura Cathedral and the night view from Mt Inasa — ranked among the world\'s three best — are the classics. Cruise to Gunkanjima and step onto the abandoned island. Champon, sara-udon and castella reflect its history as Japan\'s only open port. Its tram-and-hills exoticism exists nowhere else in Japan.',
  43: 'Kumamoto is the great caldera of Aso and Kumamoto Castle. Horses graze the grasslands of Kusasenri, and the Daikanbo lookout floats above a sea of clouds. The castle\'s restoration and the crystal springs of Shirakawa are worth the detour. Basashi horse sashimi, akaushi beef bowls and karashi renkon are the table. Add the open-air baths of Kurokawa Onsen for nature, castle and hot springs in one.',
  44: 'Oita, the self-declared "Onsen Prefecture", leads Japan in both spring sources and hot-water volume. In Beppu, tour the boiling "hells" and get buried in hot sand; in Yufuin, catch the morning mist on Lake Kinrin and browse the refined spa town. Toriten fried chicken, seki-aji and seki-saba mackerel and dango-jiru feed you between baths. If hot springs are the point of the trip, this is the summit.',
  45: 'Miyazaki is myth and subtropics. Row a boat beneath the Manai Falls in Takachiho Gorge — said to be where the gods descended — and it will stay with you. The "devil\'s washboard" rocks of Aoshima, wild horses at Cape Toi and the Nichinan coast drive are pure pleasure. Chicken nanban, charcoal-grilled jidori and mangoes are the tastes. Mild in winter, surfable all year.',
  46: 'Kagoshima is Satsuma, where the Sakurajima volcano smokes across the bay. Only here can you be buried in naturally heated sand at Ibusuki while watching an active volcano. The ancient cedars of World Heritage Yakushima and the seas of Amami are in reach. Kurobuta pork shabu-shabu, satsuma-age and imo shochu are the flavours. Rich Meiji Restoration history makes it endlessly interesting.',
  47: 'Okinawa is the old Ryukyu Kingdom and some of the world\'s finest ocean. Feel the islands\' spirituality at Shuri Castle and Sefa-utaki, then snorkel and dive the Kerama, Miyako and Ishigaki waters. Okinawa soba, goya champuru and awamori make a food culture of its own. The sea is best May–October, but winters stay around 20°C. Another country, inside Japan.',
};

const KO: Record<number, string> = {
  1: '웅대한 자연과 미식의 보고, 홋카이도. 여름에는 후라노의 라벤더밭과 비에이 언덕, 겨울에는 삿포로 눈축제와 세계 최고 수준의 파우더 스노가 기다립니다. 시레토코에서는 야생동물을, 하코다테에서는 야경과 아침시장을 즐겨 보세요. 해산물 덮밥, 징기스칸, 미소 라멘까지 — 음식만으로도 여행할 이유가 되는 땅입니다.',
  2: '네부타 축제와 쓰가루 샤미센의 고장, 아오모리. 오이라세 계류의 산책로, 도와다 호수, 그리고 일본 굴지의 벚꽃 명소 히로사키성이 있습니다. 핫코다의 수빙과 스카유 온천 등 겨울도 진합니다. 오마 참치와 사과 디저트도 놓치지 마세요. 봄 벚꽃과 8월 네부타가 특히 좋습니다.',
  3: '히라이즈미 주손지 금색당을 품은 역사와 산의 고장, 이와테. 조도가하마의 하얀 바위와 푸른 바다, 류센도 동굴의 지저호, 민화의 마을 도노 등 조용한 볼거리가 흩어져 있습니다. 왕코소바·모리오카 냉면·자자멘의 「모리오카 3대 면」에 도전해 보세요. 붐비지 않는 도호쿠의 깊은 곳입니다. 신록과 단풍철이 제철입니다.',
  4: '숲의 도시 센다이를 중심으로 바다와 산이 어우러진 미야기. 일본 3경 마쓰시마의 섬 유람, 다테 마사무네의 성하마을 산책, 자오의 화구호까지 볼거리가 이어집니다. 여름의 센다이 다나바타 축제도 유명합니다. 규탄(소혀 구이), 즌다모치, 산리쿠의 초밥까지 먹거리도 강력합니다.',
  5: '뉴토 온천향의 비탕과 나마하게의 고장, 아키타. 일본에서 가장 깊은 다자와 호수, 무가저택이 남은 가쿠노다테, 겨울 요코테의 가마쿠라 등 설국의 정취가 가득합니다. 기리탄포 전골과 이나니와 우동, 사케도 훌륭합니다. 벚꽃의 가쿠노다테와 설경 노천탕의 겨울, 모두 그림이 됩니다.',
  6: '야마데라(릿샤쿠지)의 돌계단과 자오 수빙의 고장, 야마가타. 긴잔 온천의 다이쇼 로망 거리는 눈 내리는 밤이 가장 아름답습니다. 여름엔 체리 따기, 가을엔 이모니 파티 등 계절의 즐거움이 뚜렷합니다. 요네자와규와 히야시라멘도 명물. 온천과 설경을 조용히 즐기는 여행에 어울립니다.',
  7: '아이즈의 성하마을과 반다이산의 고장, 후쿠시마. 쓰루가성과 무가저택, 옛 역참 마을 오우치주쿠, 고시키누마의 푸른 칼데라 호수들이 볼거리입니다. 기타카타 라멘의 아침 라멘 문화와 엔반 교자, 말고기 회도 별미. 우라반다이의 단풍과 겨울 설경이 특히 훌륭합니다. 도쿄에서 가까운데도 놀랄 만큼 조용합니다.',
  8: '봄의 네모필라와 가을의 코키아로 유명한 히타치 해변공원의 고장, 이바라키. 일본 3대 정원 가이라쿠엔, 후쿠로다 폭포, 우시쿠 대불 등 볼거리도 묵직합니다. 태평양의 아귀 전골과 히타치규, 낫토의 본고장이기도 합니다. 꽃철(4~5월·10월)에 맞추면 언덕 전체가 파랗고 붉게 물드는 절경을 만납니다.',
  9: '닛코 도쇼구의 호화로움과 주젠지 호수·게곤 폭포의 자연이 공존하는 도치기. 기누가와 온천에서 몸을 녹이고 우쓰노미야에서 교자 순례를 하는 것이 정석입니다. 아시카가 플라워파크의 큰 등나무(4월 말~5월)와 일루미네이션도 유명합니다. 세계유산과 온천을 한 번에 즐기려면 먼저 이곳입니다.',
  10: '구사쓰·이카호·시마 등 명탕이 모인 온천의 고장, 군마. 구사쓰의 유바타케에서 유황 김이 피어오르고, 돌계단의 이카호에서는 온천 만주를 손에 산책을. 세계유산 도미오카 제사장과 다니가와다케 로프웨이도 볼거리입니다. 미즈사와 우동과 야키만주가 명물. 설경 노천탕의 겨울과 신록의 초여름을 추천합니다.',
  11: '고에도 가와고에의 흙벽 창고 거리가 간판인 사이타마. 히카와 신사의 풍경 축제, 나가토로 뱃놀이, 지치부의 잔디벚꽃까지 당일치기 볼거리가 모여 있습니다. 12월의 지치부 요마쓰리는 일본 3대 수레 축제 중 하나. 장어와 무사시노 우동도 명물입니다. 도쿄에서 30분 만에 「에도」를 만나는 손쉬움이 매력입니다.',
  12: '나리타산 신쇼지의 문전마을과 구주쿠리 해변의 고장, 지바. 조시의 이누보사키 등대에서는 혼슈에서 가장 이른 해돋이를 볼 수 있습니다. 요로 계곡 하이킹과 가모가와·가쓰우라의 해산물도 매력. 금눈돔 조림과 가쓰우라 탄탄멘이 명물입니다. 도쿄 옆에서 어촌 마을의 공기와 등대 풍경을 만납니다.',
  13: '세계 최대급 도시이면서 골목에는 시타마치가 남아 있는 도쿄. 센소지와 나카미세, 메이지 신궁의 숲, 시부야 스크램블 교차로 등 신구의 얼굴이 몇 정거장마다 바뀝니다. 스시·라멘·튀김, 미슐랭 별 수는 세계 1위. 미술관도 밤거리도 깊이가 끝이 없습니다. 몇 번을 와도 「처음의 도쿄」가 있습니다.',
  14: '요코하마의 항구, 가마쿠라의 고도, 하코네의 온천까지 세 얼굴의 가나가와. 가마쿠라 대불과 에노덴 차창, 하코네 아시노코와 오와쿠다니, 요코하마 중화거리 먹방이 정석입니다. 아시노코 너머 후지산은 맑은 겨울이 가장 아름답습니다. 도쿄에서 1시간에 바다·산·온천이 모두 갖춰집니다.',
  15: '쌀과 술의 나라, 니가타. 사케 양조장이 약 90곳으로 일본 최다이며 역 안 「폰슈칸」에서 시음을 즐길 수 있습니다. 여름엔 사도섬의 맑은 바다와 다라이부네, 겨울엔 나에바·유자와의 상질의 눈. 헤기소바와 노도구로, 도치오의 유부도 명물입니다. 8월 나가오카 불꽃놀이는 평생 기억에 남을 스케일입니다.',
  16: '다테야마 구로베 알펜루트의 「눈의 대계곡」으로 유명한 도야마. 3,000m급 산들과 도야마만이 가까워, 아마하라시 해안에서는 바다 너머 다테야마 연봉이 보입니다. 도야마만의 흰새우·반딧불오징어·겨울 방어는 신선도가 남다릅니다. 세계에서 가장 아름다운 스타벅스로 불리는 간스이 공원도 인기. 눈의 벽은 4~6월 한정 절경입니다.',
  17: '가나자와의 겐로쿠엔과 찻집 거리를 품은 공예와 미식의 고장, 이시카와. 히가시 차야가이에서 금박 아이스크림을 들고 걷고, 21세기 미술관에서 현대미술을 감상하세요. 와지마 칠기와 구타니야키 등 전통공예 체험도 풍부합니다. 오미초 시장의 해산물 덮밥과 노도구로는 필수. 눈 덮인 겐로쿠엔의 겨울도 운치 있습니다.',
  18: '도진보의 절벽과 공룡 왕국, 후쿠이. 후쿠이 공룡박물관은 세계 3대 공룡박물관 중 하나로 가족 여행객에게 큰 인기입니다. 조동종 대본산 에이헤이지에서는 고요한 아침 예불을 볼 수 있습니다. 에치젠 게(겨울)와 오로시소바, 소스 가츠동이 명물. 관광객이 적어 조용한 호쿠리쿠를 독차지할 수 있습니다.',
  19: '후지산을 가장 아름답게 바라보는 고장, 야마나시. 가와구치 호수에 비친 후지산과 아라쿠라야마 센겐공원의 오층탑 풍경은 세계적으로 유명합니다. 포도와 와인의 가쓰누마, 호토 전골, 복숭아 따기 등 먹거리도 충실합니다. 후지 5호에서의 캠핑과 사우나도 인기. 공기가 맑은 늦가을~겨울이 후지산의 베스트 시즌입니다.',
  20: '3,000m급 봉우리가 이어지는 산의 왕국, 나가노. 가미코치의 아즈사강과 호타카 연봉, 온천에 몸을 담그는 지고쿠다니의 스노 몽키, 마쓰모토성과 젠코지까지 볼거리가 끝이 없습니다. 여름은 피서와 트레킹, 겨울은 하쿠바·노자와 스키와 설경 온천. 신슈 소바와 노자와나, 사과도 명물입니다. 산을 좋아한다면 먼저 이곳입니다.',
  21: '시라카와고의 갓쇼즈쿠리와 성하마을 히다 다카야마의 고장, 기후. 옛 거리에서 히다규 초밥을 맛보고 아침시장을 구경하는 것이 정석입니다. 게로 온천은 일본 3대 명탕 중 하나. 나가라강의 우카이(가마우지 낚시, 5~10월)는 1,300년 이어진 여름 풍물시입니다. 눈 덮인 시라카와고의 라이트업은 겨울만의 선물입니다.',
  22: '후지산과 스루가만 사이, 차와 와사비의 고장 시즈오카. 미호노마쓰바라에서 바라보는 후지, 니혼다이라의 차밭, 이즈의 온천과 해안선이 볼거리입니다. 스루가만의 벚꽃새우와 시라스, 장어, 시즈오카 오뎅까지 먹거리도 풍부합니다. 아타미와 슈젠지는 도쿄에서 신칸센으로 금방. 후지산을 바라보는 노천탕은 각별합니다.',
  23: '나고야 메시의 본고장, 아이치. 미소카츠·히츠마부시·데바사키·모닝 문화 등 음식 개성은 전국 최고 수준입니다. 금 샤치호코의 나고야성, 도쿠가와 미술관, 지브리 파크까지 볼거리도 다채롭습니다. 미카와만의 예술 섬 사쿠시마도 인기 상승 중. 거리 산책과 먹방 중심의 여행이 어울립니다.',
  24: '이세 신궁의 고장, 미에. 「평생에 한 번은 이세 참배」의 목적지로, 오카게요코초 먹거리 골목도 즐거움입니다. 메오토이와의 해돋이, 해녀 문화가 남은 도바·시마, 리아스식 해안 아고만도 볼거리. 마쓰사카규와 이세에비, 데코네즈시까지 먹거리도 일급입니다. 차가운 겨울 이른 아침의 참배가 특히 상쾌합니다.',
  25: '일본 최대 호수 비와코를 품은 시가. 호수에 도리이가 떠 있는 시라히게 신사, 국보 히코네성, 히에이잔 엔랴쿠지 등 물과 역사의 볼거리가 이어집니다. 오미규는 일본에서 가장 오래된 와규 브랜드. 호반 자전거길 「비와이치」는 라이더의 성지입니다. 교토에서 겨우 10분이면 이 고요함을 만납니다.',
  26: '천 년의 수도, 교토. 후시미 이나리의 센본도리이, 금각사, 기요미즈의 무대까지 명소를 꼽자면 끝이 없습니다. 벚꽃과 단풍은 각별히 아름답지만 그만큼 붐빕니다. 아침의 대나무숲과 밤의 폰토초처럼 시간을 비켜 걷는 것이 고수의 방법. 유도후에서 가이세키, 말차 디저트까지 음식도 우아합니다.',
  27: '「먹다 망하는」 도시, 오사카. 도톤보리의 네온과 글리코 간판 아래 다코야키·오코노미야키·구시카츠를 순례하는 것이 왕도입니다. 오사카성, 쓰텐카쿠, 유니버설 스튜디오 재팬까지 놀 거리도 가득합니다. 정 많은 거리 분위기는 일본 제일. 밤이 긴 여행, 웃음과 음식의 여행이라면 이곳입니다.',
  28: '백로성이라 불리는 세계유산 히메지성의 고장, 효고. 이국 정서의 고베 거리, 롯코산의 천만 달러 야경, 기노사키 온천의 외탕 순례까지 면면이 다채롭습니다. 고베규와 아카시야키, 나다의 사케도 빼놓을 수 없습니다. 아리마 온천은 도요토미 히데요시도 사랑한 유서 깊은 명탕. 도시·성·온천을 한 번에 즐깁니다.',
  29: '대불과 사슴의 고도, 나라. 도다이지 대불전, 사슴이 인사하는 나라 공원, 주홍빛 가스가타이샤가 정석입니다. 조금 더 가면 산 전체가 벚꽃으로 물드는 요시노산(4월), 일본에서 가장 오래된 길 야마노베노미치도 있습니다. 감잎 초밥과 구즈모치가 명물. 교토보다 한산해 더 오래된 일본을 만납니다.',
  30: '구마노 고도와 고야산, 기도의 고장 와카야마. 삼나무 숲 참배길을 걷고 숙방에 묵으며 정진요리와 아침 예불을 체험할 수 있습니다. 나치 폭포와 주홍빛 탑의 대비는 숨이 멎을 아름다움. 시라하마의 백사장과 판다, 가쓰우라의 참치도 매력입니다. 걷는 여행, 마음을 고르는 여행에 어울립니다.',
  31: '일본 최대급 모래 바다, 돗토리 사구의 고장. 사구에서는 낙타 유람과 샌드보드를 즐기고, 옆의 모래 미술관에서는 모래 조각을 감상할 수 있습니다. 『게게게의 기타로』의 미즈키 시게루 로드, 흰 벽 창고의 구라요시도 볼거리. 겨울의 마쓰바 게와 20세기 배가 명물입니다. 전국에서 손꼽히게 한적한 것 — 그것이 사치입니다.',
  32: '인연의 신 이즈모타이샤의 고장, 시마네. 신들이 모인다는 신사에 참배하고 신지 호수의 석양을 바라보는 것이 왕도입니다. 세계유산 이와미 은광, 해자 유람의 마쓰에성, 정원 일본 제일의 아다치 미술관까지 묵직한 볼거리가 모여 있습니다. 이즈모 소바와 재첩국이 명물. 신재월(음력 10월)의 참배는 각별합니다.',
  33: '「맑음의 나라」 오카야마. 흰 벽과 버드나무의 구라시키 미관지구, 일본 3대 정원 고라쿠엔과 까마귀성(오카야마성)이 간판입니다. 세토내해의 이누지마·데시마 아트 여행의 관문이기도 합니다. 백도와 머스캣, 바라즈시 등 과일 왕국다운 먹거리도 매력. 비가 적어 일 년 내내 실패가 적은 여행지입니다.',
  34: '원폭 돔과 이쓰쿠시마 신사, 두 세계유산의 히로시마. 바다에 뜬 미야지마의 대도리이는 만조와 간조에 다른 얼굴을 보여줍니다. 오코노미야키와 굴, 오노미치 라멘 등 먹거리도 강자들입니다. 시마나미 해도 사이클링은 세토내해의 다도해 풍경을 온몸으로 느끼게 해 줍니다. 역사와 마주하고 바다에 치유되는 여행입니다.',
  35: '혼슈 최서단의 야마구치. 긴타이교의 5연 아치, CNN이 「일본에서 가장 아름다운 곳」으로 꼽은 모토노스미 신사의 붉은 도리이 행렬, 아키요시다이 카르스트 대지까지 사진 찍고 싶은 풍경이 이어집니다. 시모노세키의 복어는 본고장 중의 본고장. 하기의 성하마을에서는 막말 지사들의 발자취를 따라갈 수 있습니다.',
  36: '아와오도리와 나루토 소용돌이의 고장, 도쿠시마. 8월의 아와오도리 때는 도시 전체가 춤판이 됩니다. 이야 계곡의 덩굴다리와 깊은 협곡은 일본 3대 비경 중 하나. 나루토 해협의 소용돌이는 배에서도 유리 바닥 산책로에서도 볼 수 있습니다. 도쿠시마 라멘과 스다치, 나루토 도미가 명물입니다.',
  37: '「우동현」 가가와. 아침부터 제면소를 순례하는 사누키 우동 여행이 명물입니다. 세토우치 국제예술제의 나오시마·데시마는 세계에 알려진 예술의 성지. 미슐랭 3스타의 리쓰린 공원, 곤피라산의 785 돌계단도 볼거리입니다. 일본에서 가장 작은 현에 음식과 예술이 꽉 차 있습니다.',
  38: '도고 온천의 고장, 에히메. 『센과 치히로』의 모델로도 불리는 도고온센 본관에서 목욕하고 유카타 차림으로 상점가를 걷는 것이 정석입니다. 현존 12천수의 마쓰야마성, 시마나미 해도의 섬들, 우와카이의 계단밭도 볼거리. 도미밥과 귤은 본고장의 맛입니다. 문학의 도시 마쓰야마에서 시키의 발자취도 따라가 보세요.',
  39: '마지막 청류 시만토강의 고장, 고치. 침하교를 자전거로 건너고 카누로 강을 내려가는 여행이 가능합니다. 요사코이 축제(8월)와 일요시장, 가쓰라하마의 사카모토 료마 동상도 정석. 짚불에 구운 가다랑어 다타키는 향부터 다릅니다. 가시와지마의 바다 투명도는 오키나와급. 호쾌한 음식과 물놀이, 여름이 가장 어울리는 곳입니다.',
  40: '포장마차의 도시, 후쿠오카. 나카스 강변의 야타이에서 돈코츠 라멘과 야키라멘을 순례하는 밤이 명물입니다. 다자이후 텐만구의 매화, 이토시마의 바닷가 카페, 야나가와 뱃놀이 등 당일치기도 충실합니다. 모츠나베·명란·우동까지 음식의 층이 규슈 제일. 공항에서 시내까지 지하철 5분의 가까움도 매력입니다.',
  41: '아리타야키·이마리야키의 고향, 사가. 가마터 마을을 걷고 물레 체험과 그릇 쇼핑을 즐길 수 있습니다. 요부코 아침시장에서는 투명한 오징어 활어회를. 벼랑에 지은 유토쿠 이나리 신사와 가을의 벌룬 페스타(11월)도 볼거리입니다. 우레시노·다케오 온천도 명탕. 그릇과 음식을 사랑하는 사람의 고장입니다.',
  42: '언덕과 교회의 항구 도시, 나가사키. 글로버 정원과 오우라 천주당, 이나사야마의 세계 신 3대 야경이 정석입니다. 군칸지마 크루즈로 폐허의 섬에 상륙할 수 있습니다. 짬뽕·사라우동·카스텔라 등 쇄국 시대 유일한 창구다운 음식도 매력. 노면전차로 도는 이국 정서는 일본 어디에도 없습니다.',
  43: '아소의 대칼데라와 구마모토성의 고장, 구마모토. 세계 최대급 칼데라를 말이 달리는 구사센리, 운해의 다이칸보 등 스케일 큰 풍경이 이어집니다. 복원이 진행 중인 구마모토성, 물 맑은 시라카와 수원도 볼거리. 말고기 회와 아카우시 덮밥, 가라시렌콘이 명물입니다. 구로카와 온천의 노천탕 순례를 더하면 자연·성·온천이 한 번에 갖춰집니다.',
  44: '원천 수와 용출량 모두 일본 제일의 「온천현」 오이타. 벳푸에서는 지옥 순례와 모래찜질을, 유후인에서는 긴린코의 아침 안개와 세련된 온천 거리를 즐깁니다. 도리텐과 세키아지·세키사바, 단고지루가 명물. 유후인의 단풍과 설경 노천탕의 겨울이 특히 운치 있습니다. 온천이 여행의 목적이라면 이곳이 정점입니다.',
  45: '신화와 남국의 고장, 미야자키. 천손강림의 땅 다카치호 협곡에서 보트를 저으며 마나이 폭포를 올려다보는 체험은 유일무이합니다. 도깨비 빨래판이 펼쳐진 아오시마, 도이곶의 야생마, 니치난 해안 드라이브도 상쾌합니다. 치킨난반과 토종닭 숯불구이, 망고가 명물. 겨울에도 온난해 일 년 내내 서핑이 가능합니다.',
  46: '사쿠라지마가 연기를 올리는 사쓰마의 나라, 가고시마. 긴코만 너머 활화산을 바라보며 천연 모래찜질 온천(이부스키)에 묻히는 체험은 이곳뿐입니다. 세계유산 야쿠시마의 조몬 삼나무, 아마미의 바다까지 자연의 스케일이 남다릅니다. 흑돼지 샤브샤브와 사쓰마아게, 고구마 소주가 명물. 유신의 역사도 짙은, 볼거리가 마르지 않는 곳입니다.',
  47: '류큐 왕국의 자취와 세계 굴지의 바다, 오키나와. 슈리성과 세화우타키에서 류큐의 기도를 느끼고, 게라마·미야코·이시가키의 바다에서 스노클링과 다이빙을. 오키나와 소바와 고야참프루, 아와모리 등 음식 문화도 독자적입니다. 바다는 5~10월이 최고지만 겨울에도 20도 안팎으로 온난합니다. 일본 속의 또 하나의 나라입니다.',
};

const ZH_HANS: Record<number, string> = {
  1: '北海道是壮阔自然与美食的宝库。夏天有富良野的薰衣草田和美瑛的丘陵，冬天有札幌雪祭和世界顶级的粉雪。在知床邂逅野生动物，在函馆欣赏夜景、逛早市。海鲜盖饭、成吉思汗烤肉、味噌拉面——光是美食就值得一游。',
  2: '青森是睡魔祭与津轻三味线的故乡。走一走奥入濑溪流的步道，游十和田湖，再到日本屈指可数的赏樱名所弘前城。八甲田的树冰和酸汤温泉让冬天同样精彩。别错过大间金枪鱼和苹果甜点。春樱和八月的睡魔祭尤其推荐。',
  3: '岩手拥有平泉中尊寺金色堂，是历史与山岳之县。净土滨的白岩碧海、龙泉洞的地底湖、民间故事之乡远野等安静的景点散布各处。不妨挑战「盛冈三大面」：碗子荞麦面、盛冈冷面和炸酱面。这里能避开人潮，品味东北深处。新绿和红叶季节最佳。',
  4: '宫城以「森林之都」仙台为中心，山海兼备。游日本三景之一的松岛群岛，漫步伊达政宗的城下町，再看藏王的御釜火口湖。夏天的仙台七夕祭也很有名。牛舌、毛豆麻糬和三陆寿司让餐桌同样丰盛。',
  5: '秋田有乳头温泉乡的秘汤和生剥鬼的传说。日本最深的田泽湖、保留武家宅邸的角馆、冬天横手的雪屋，雪国风情满满。烤米棒火锅、稻庭乌冬和好酒一应俱全。樱花时节的角馆和雪见露天温泉的冬天，都美得像画。适合想安静旅行的人。',
  6: '山形有山寺（立石寺）的千级石阶和藏王树冰。银山温泉大正浪漫的街道，雪夜最美。夏天摘樱桃，秋天在河边办芋煮会，四季乐趣分明。米泽牛和冷拉面是名物。适合安静地享受温泉与雪景的旅程。',
  7: '福岛是会津的城下町与磐梯山之县。鹤城与武家宅邸、保留驿站风貌的大内宿、五色沼的蓝色火山湖群都值得一看。喜多方拉面的「早晨拉面」文化、圆盘饺子和马肉刺身也很地道。里磐梯的红叶和冬雪尤其出色。离东京不远，却出奇地安静。',
  8: '茨城以国营日立海滨公园闻名——春天粉蝶花把山丘染成蓝色，秋天扫帚草染成绯红。日本三名园之一的偕乐园、袋田瀑布、牛久大佛都是硬核景点。太平洋的鮟鱇火锅、常陆牛，还有纳豆的本场。对准花期（4-5月、10月）前往，就能看到漫山花海。',
  9: '栃木同时拥有日光东照宫的金碧辉煌与中禅寺湖、华严瀑布的自然美景。在鬼怒川温泉暖暖身子，再到宇都宫吃一轮饺子是经典行程。足利花卉公园的大紫藤（4月底-5月）和灯光秀也很有名。想一次游览世界遗产和温泉，先来这里。',
  10: '群马是名汤云集的温泉县：草津、伊香保、四万。草津的汤畑硫磺蒸气袅袅，伊香保的石阶街可以边泡汤边吃温泉馒头。世界遗产富冈制丝厂、谷川岳缆车也是看点。水泽乌冬和烤馒头是名物。推荐雪见露天的冬天和新绿的初夏。',
  11: '埼玉的招牌是「小江户」川越的土藏老街。冰川神社的风铃、长瀞的游船、秩父的芝樱，一日游景点齐全。12月的秩父夜祭是日本三大曳山祭之一。鳗鱼和武藏野乌冬也是名物。从东京30分钟就能遇见「江户」。',
  12: '千叶有成田山新胜寺的门前町和九十九里海岸。在铫子的犬吠埼灯塔，可以迎来本州最早的日出。养老溪谷的徒步、鸭川和胜浦的海鲜也很有魅力。名物是炖金目鲷和胜浦担担面。就在东京旁边，却有渔港小镇的空气和灯塔风景。',
  13: '东京是世界最大级的都市，钻进小巷却仍有下町风情。浅草寺与仲见世、明治神宫的森林、涩谷全向十字路口——新旧面孔几站地铁就切换一次。寿司、拉面、天妇罗，米其林星星数世界第一。美术馆与夜生活同样深不见底。无论来多少次，都能遇见「初次见面的东京」。',
  14: '神奈川有三副面孔：港城横滨、古都镰仓、温泉乡箱根。看镰仓大佛、坐江之电沿海行驶，游芦之湖、看大涌谷喷烟，再到横滨中华街边走边吃。隔着芦之湖的富士山，晴朗的冬日最清晰。从东京1小时，海、山、温泉全都有。',
  15: '新潟是米与酒之国。清酒酒藏约90家为全国最多，车站里的「PONSHU馆」可以品酒。夏天有佐渡岛清澈的海与盆舟，冬天有苗场、汤泽的优质雪。片木荞麦面、喉黑鱼、栃尾油豆腐都是名物。8月的长冈花火，一生难忘。',
  16: '富山以立山黑部阿尔卑斯路线的「雪之大谷」闻名。3000米级群山紧邻富山湾，从雨晴海岸可以隔海远眺立山连峰。富山湾的白虾、萤火鱿、寒鰤鲜度出众。被称为世界最美星巴克的环水公园也很受欢迎。雪墙是4-6月限定的绝景。',
  17: '石川是金泽：兼六园、茶屋街与深厚的工艺传统。在东茶屋街拿着金箔冰淇淋散步，再到21世纪美术馆看当代艺术。轮岛涂、九谷烧等传统工艺体验也很丰富。近江町市场的海鲜盖饭和喉黑鱼必吃。雪吊装点的兼六园，冬天别有风情。',
  18: '福井有东寻坊的断崖，更是恐龙王国——福井县立恐龙博物馆是世界三大恐龙博物馆之一，深受亲子游客欢迎。在曹洞宗大本山永平寺，可以参观静谧的晨课。名物是越前蟹（冬）、萝卜泥荞麦面和酱汁猪排饭。游客稀少，安静的北陆任你独享。',
  19: '山梨是眺望富士山最美的县。河口湖的「逆富士」倒影、新仓山浅间公园五重塔与富士的同框举世闻名。胜沼的葡萄与葡萄酒、饩饨面火锅、摘桃子让味蕾也满足。富士五湖的露营和桑拿也很流行。空气清澈的深秋到冬天是富士山的最佳季节。',
  20: '长野是3000米级群峰连绵的山岳王国。上高地的梓川与穗高连峰、地狱谷泡温泉的雪猴、松本城与善光寺，看点数不尽。夏天避暑徒步，冬天到白马、野泽滑雪、泡雪见温泉。信州荞麦面、野泽菜和苹果是招牌。爱山的人，先来这里。',
  21: '岐阜有白川乡的合掌造和城下町飞驒高山。在老街吃飞驒牛握寿司、逛早市是经典玩法。下吕温泉是日本三名泉之一。长良川鹈饲（5-10月）是延续1300年的夏日风物诗。雪中白川乡的点灯，是冬天限定的犒赏。',
  22: '静冈夹在富士山与骏河湾之间，是茶与山葵之县。三保松原远眺富士、日本平的茶田、伊豆的温泉与海岸线都是看点。骏河湾的樱花虾、银鱼、鳗鱼和静冈关东煮让餐桌丰盛。热海、修善寺从东京坐新干线转眼即到。边看富士山边泡露天温泉，无与伦比。',
  23: '爱知是名古屋美食的大本营：味噌猪排、鳗鱼三吃、炸鸡翅和独特的早餐文化，个性全国屈指可数。金鯱的名古屋城、德川美术馆、吉卜力公园等看点也多彩。三河湾的艺术小岛佐久岛人气上升中。适合以城市漫步和吃遍美食为轴的旅行。',
  24: '三重是伊势神宫之县，日本人「一生一次伊势参拜」的目的地，托福横丁的边走边吃也是乐趣。夫妇岩的日出、保留海女文化的鸟羽与志摩、里亚斯海岸的英虞湾都值得一看。松阪牛、伊势龙虾、手捏寿司都是一流。凛冽冬晨的参拜尤其清爽。',
  25: '滋贺环抱日本第一大湖琵琶湖。湖中浮着鸟居的白鬚神社、国宝彦根城、比叡山延历寺，水与历史的景点一字排开。近江牛是日本最古老的和牛品牌。环湖骑行路线「琵琶一」是骑行者的圣地。从京都只需10分钟，就能遇见这份宁静。',
  26: '京都，千年之都。伏见稻荷的千本鸟居、金阁寺、清水的舞台——名胜数之不尽。樱花与红叶美得出众，人潮也随之而来；清晨的竹林、夜晚的先斗町，错峰而行才是行家走法。从汤豆腐到怀石、抹茶甜点，连饮食都风雅。',
  27: '大阪，「吃到破产」之城。道顿堀的霓虹和格力高招牌下，章鱼烧、大阪烧、串炸一路吃过去才是王道。大阪城、通天阁、日本环球影城，玩乐场所也齐全。街头亲切热络的空气日本第一。想要夜生活长、充满欢笑与美食的旅行，就来这里。',
  28: '兵库拥有被称为白鹭城的世界遗产姬路城。神户异国情调的街区、六甲山的千万美元夜景、城崎温泉的外汤巡游，阵容多彩。神户牛、明石烧、滩之清酒不可错过。有马温泉是丰臣秀吉钟爱的日本最古老名汤之一。城市、城堡、温泉一次满足。',
  29: '奈良是大佛与鹿的古都。东大寺大佛殿、鹿会鞠躬的奈良公园、朱红的春日大社是经典路线。稍走远些，还有4月漫山樱花的吉野山和日本最古老的道路「山之边之道」。柿叶寿司和葛饼是名物。比京都人少，能遇见更古老的日本。',
  30: '和歌山是熊野古道与高野山的祈祷之县。走过杉木参道，宿坊过夜，体验精进料理和晨间诵经。那智瀑布与朱红宝塔的同框美得屏息。白滨的沙滩与熊猫、胜浦的金枪鱼也是亮点。适合喜欢徒步、想让身心归位的人。',
  31: '鸟取拥有日本最大级的沙丘。可以骑骆驼、玩滑沙，再到旁边的沙之美术馆欣赏沙雕艺术。《鬼太郎》的水木茂之路、白壁土藏的仓吉也值得一逛。冬天的松叶蟹和二十世纪梨是名物。游客之少全国屈指——这正是奢侈所在。',
  32: '岛根是结缘之神出云大社的故乡。参拜传说中众神聚集的神社，再看宍道湖的夕阳是王道。世界遗产石见银山、护城河游船的松江城、庭园日本第一的足立美术馆，深度景点云集。出云荞麦面和蚬汤是名物。神在月（旧历10月）的参拜别具意义。',
  33: '「晴天之国」冈山。白壁垂柳的仓敷美观地区、日本三名园的后乐园与乌城（冈山城）是招牌。这里也是前往犬岛、丰岛艺术之旅的门户。白桃、麝香葡萄、散寿司不负水果王国之名。少雨的气候，让这里一年四季都少有失手。',
  34: '广岛拥有两处世界遗产：原爆圆顶馆与严岛神社。宫岛海上的大鸟居，涨潮退潮各有一番面貌。广岛烧、牡蛎、尾道拉面，美食阵容同样强大。骑行岛波海道，用身体感受濑户内海的多岛之美。这是一场直面历史、被大海治愈的旅行。',
  35: '本州最西端的山口。锦带桥的五连拱、被CNN评为「日本最美地方」之一的元乃隅神社红色鸟居长阵、秋吉台的喀斯特台地，处处上镜。下关的河豚是本场中的本场。在萩的城下町，可以追寻幕末志士的足迹。安静而浓厚，是行家偏爱之县。',
  36: '德岛是阿波舞与鸣门漩涡之乡。8月的阿波舞节，全城变成舞池。祖谷的藤蔓桥与深谷是日本三大秘境之一。鸣门海峡的漩涡，坐船或走玻璃地板步道都能看。德岛拉面、酢橘、鸣门鲷是名物。夏日祭典加秘境漫步，是这里的两大主轴。',
  37: '「乌冬县」香川。从早上就开始逐家品尝制面所的赞岐乌冬巡礼是名物。濑户内国际艺术祭的直岛、丰岛是世界闻名的艺术圣地。米其林三星的栗林公园、金刀比罗宫的785级石阶也是看点。日本最小的县，塞满了美食与艺术。',
  38: '爱媛是道后温泉之乡。在被称为《千与千寻》原型之一的道后温泉本馆泡汤，再穿浴衣逛商店街是经典玩法。现存12天守之一的松山城、岛波海道的群岛、宇和海的梯田海岸也是看点。鲷鱼饭和蜜柑是本场之味。在文学之城松山，还能追寻正冈子规的足迹。',
  39: '高知是「最后的清流」四万十川之县。骑车过沉下桥、划独木舟顺流而下的旅行只此一家。8月的夜来祭、周日集市、桂滨的坂本龙马像也是经典。稻草炙烤的鲣鱼半敲烧，从香气就与众不同。柏岛的海水透明度堪比冲绳。豪爽的美食与戏水，最适合夏天。',
  40: '福冈是屋台（路边摊）之城。在中洲河畔的屋台，从豚骨拉面吃到炒拉面的夜晚是名物。太宰府天满宫的梅花、糸岛的海边咖啡馆、柳川的游船，一日游也很充实。牛杂锅、明太子、乌冬面——美食底蕴九州第一。机场到市区地铁5分钟的便利也是魅力。',
  41: '佐贺是有田烧、伊万里烧的故乡。漫步窑元小镇，体验拉坯、选购器皿。呼子的早市有透明的活鱿鱼刺身。悬崖上的祐德稻荷神社和秋天的热气球节（11月）也是看点。嬉野、武雄的温泉同样是名汤。这里属于热爱器物与美食的人。',
  42: '长崎是坡道与教堂的港城。哥拉巴园、大浦天主堂、稻佐山的「世界新三大夜景」是经典。乘军舰岛巡航，可以登上废墟之岛。强棒面、皿乌冬、蜂蜜蛋糕——锁国时代唯一窗口孕育的和华兰美食也是魅力。乘路面电车游走的异国情调，日本别处找不到。',
  43: '熊本是阿苏大破火山口与熊本城之县。马群奔跑的草千里、云海之上的大观峰，大尺度的风景接连不断。复建中的熊本城、清澈的白川水源也值得一看。马肉刺身、红牛盖饭、芥末莲藕是名物。再加上黑川温泉的露天巡汤，自然、城堡、温泉一次到位。',
  44: '大分是源泉数与涌出量均为日本第一的「温泉县」。在别府巡游「地狱」、体验沙浴；在由布院看金鳞湖的晨雾、逛精致的温泉街。炸鸡天妇罗、关鲹关鲭、团子汁是名物。由布院的红叶和雪见露天的冬天尤其有风情。若温泉是旅行的目的，这里就是顶点。',
  45: '宫崎是神话与南国之县。在天孙降临之地高千穗峡划船仰望真名井瀑布，体验独一无二。鬼之洗衣板铺展的青岛、都井岬的野生马、日南海岸兜风都令人畅快。鸡南蛮、地鸡炭火烧、芒果是名物。冬天也温暖，一年四季都能冲浪。',
  46: '鹿儿岛是樱岛喷烟的萨摩之国。一边眺望锦江湾对岸的活火山，一边在指宿埋进天然砂蒸温泉，这体验仅此一处。世界遗产屋久岛的绳文杉、奄美的大海都在范围内，自然尺度非凡。黑豚涮涮锅、萨摩炸鱼饼、芋烧酒是名物。维新历史浓厚，看点无穷。',
  47: '冲绳保留着琉球王国的面影，拥有世界屈指的大海。在首里城和斋场御岳感受琉球的祈祷，再到庆良间、宫古、石垣的海域浮潜与潜水。冲绳荞麦面、苦瓜炒什锦、泡盛，饮食文化自成一派。海的最佳季节是5-10月，冬天也有20度上下的温暖。这是日本之中的另一个国度。',
};

const ZH_HANT: Record<number, string> = {
  1: '北海道是壯闊自然與美食的寶庫。夏天有富良野的薰衣草田和美瑛的丘陵，冬天有札幌雪祭和世界頂級的粉雪。在知床邂逅野生動物，在函館欣賞夜景、逛早市。海鮮蓋飯、成吉思汗烤肉、味噌拉麵——光是美食就值得一遊。',
  2: '青森是睡魔祭與津輕三味線的故鄉。走一走奧入瀨溪流的步道，遊十和田湖，再到日本屈指可數的賞櫻名所弘前城。八甲田的樹冰和酸湯溫泉讓冬天同樣精彩。別錯過大間鮪魚和蘋果甜點。春櫻和八月的睡魔祭尤其推薦。',
  3: '岩手擁有平泉中尊寺金色堂，是歷史與山岳之縣。淨土濱的白岩碧海、龍泉洞的地底湖、民間故事之鄉遠野等安靜的景點散布各處。不妨挑戰「盛岡三大麵」：碗子蕎麥麵、盛岡冷麵和炸醬麵。這裡能避開人潮，品味東北深處。新綠和紅葉季節最佳。',
  4: '宮城以「森林之都」仙台為中心，山海兼備。遊日本三景之一的松島群島，漫步伊達政宗的城下町，再看藏王的御釜火口湖。夏天的仙台七夕祭也很有名。牛舌、毛豆麻糬和三陸壽司讓餐桌同樣豐盛。',
  5: '秋田有乳頭溫泉鄉的秘湯和生剝鬼的傳說。日本最深的田澤湖、保留武家宅邸的角館、冬天橫手的雪屋，雪國風情滿滿。烤米棒火鍋、稻庭烏龍麵和好酒一應俱全。櫻花時節的角館和雪見露天溫泉的冬天，都美得像畫。適合想安靜旅行的人。',
  6: '山形有山寺（立石寺）的千級石階和藏王樹冰。銀山溫泉大正浪漫的街道，雪夜最美。夏天摘櫻桃，秋天在河邊辦芋煮會，四季樂趣分明。米澤牛和冷拉麵是名物。適合安靜地享受溫泉與雪景的旅程。',
  7: '福島是會津的城下町與磐梯山之縣。鶴城與武家宅邸、保留驛站風貌的大內宿、五色沼的藍色火山湖群都值得一看。喜多方拉麵的「早晨拉麵」文化、圓盤煎餃和馬肉刺身也很道地。裏磐梯的紅葉和冬雪尤其出色。離東京不遠，卻出奇地安靜。',
  8: '茨城以國營日立海濱公園聞名——春天粉蝶花把山丘染成藍色，秋天掃帚草染成緋紅。日本三名園之一的偕樂園、袋田瀑布、牛久大佛都是硬底子景點。太平洋的鮟鱇火鍋、常陸牛，還有納豆的本場。對準花期（4-5月、10月）前往，就能看到漫山花海。',
  9: '栃木同時擁有日光東照宮的金碧輝煌與中禪寺湖、華嚴瀑布的自然美景。在鬼怒川溫泉暖暖身子，再到宇都宮吃一輪煎餃是經典行程。足利花卉公園的大紫藤（4月底-5月）和燈飾也很有名。想一次遊覽世界遺產和溫泉，先來這裡。',
  10: '群馬是名湯雲集的溫泉縣：草津、伊香保、四萬。草津的湯畑硫磺蒸氣裊裊，伊香保的石階街可以邊泡湯邊吃溫泉饅頭。世界遺產富岡製絲廠、谷川岳纜車也是看點。水澤烏龍麵和烤饅頭是名物。推薦雪見露天的冬天和新綠的初夏。',
  11: '埼玉的招牌是「小江戶」川越的土藏老街。冰川神社的風鈴、長瀞的遊船、秩父的芝櫻，一日遊景點齊全。12月的秩父夜祭是日本三大曳山祭之一。鰻魚和武藏野烏龍麵也是名物。從東京30分鐘就能遇見「江戶」。',
  12: '千葉有成田山新勝寺的門前町和九十九里海岸。在銚子的犬吠埼燈塔，可以迎來本州最早的日出。養老溪谷的健行、鴨川和勝浦的海鮮也很有魅力。名物是燉金目鯛和勝浦擔擔麵。就在東京旁邊，卻有漁港小鎮的空氣和燈塔風景。',
  13: '東京是世界最大級的都市，鑽進小巷卻仍有下町風情。淺草寺與仲見世、明治神宮的森林、澀谷全向十字路口——新舊面孔幾站地鐵就切換一次。壽司、拉麵、天婦羅，米其林星星數世界第一。美術館與夜生活同樣深不見底。無論來幾次，都能遇見「初次見面的東京」。',
  14: '神奈川有三副面孔：港城橫濱、古都鎌倉、溫泉鄉箱根。看鎌倉大佛、坐江之電沿海行駛，遊蘆之湖、看大涌谷噴煙，再到橫濱中華街邊走邊吃。隔著蘆之湖的富士山，晴朗的冬日最清晰。從東京1小時，海、山、溫泉全都有。',
  15: '新潟是米與酒之國。清酒酒藏約90家為全國最多，車站裡的「PONSHU館」可以品酒。夏天有佐渡島清澈的海與盆舟，冬天有苗場、湯澤的優質雪。片木蕎麥麵、喉黑魚、栃尾油豆腐都是名物。8月的長岡花火，一生難忘。',
  16: '富山以立山黑部阿爾卑斯路線的「雪之大谷」聞名。3000公尺級群山緊鄰富山灣，從雨晴海岸可以隔海遠眺立山連峰。富山灣的白蝦、螢火魷、寒鰤鮮度出眾。被稱為世界最美星巴克的環水公園也很受歡迎。雪牆是4-6月限定的絕景。',
  17: '石川就是金澤：兼六園、茶屋街與深厚的工藝傳統。在東茶屋街拿著金箔冰淇淋散步，再到21世紀美術館看當代藝術。輪島塗、九谷燒等傳統工藝體驗也很豐富。近江町市場的海鮮蓋飯和喉黑魚必吃。雪吊裝點的兼六園，冬天別有風情。',
  18: '福井有東尋坊的斷崖，更是恐龍王國——福井縣立恐龍博物館是世界三大恐龍博物館之一，深受親子旅客歡迎。在曹洞宗大本山永平寺，可以參觀靜謐的晨課。名物是越前蟹（冬）、蘿蔔泥蕎麥麵和醬汁豬排飯。遊客稀少，安靜的北陸任你獨享。',
  19: '山梨是眺望富士山最美的縣。河口湖的「逆富士」倒影、新倉山淺間公園五重塔與富士的同框舉世聞名。勝沼的葡萄與葡萄酒、餺飥麵火鍋、採桃體驗讓味蕾也滿足。富士五湖的露營和三溫暖也很流行。空氣清澈的深秋到冬天是富士山的最佳季節。',
  20: '長野是3000公尺級群峰連綿的山岳王國。上高地的梓川與穗高連峰、地獄谷泡溫泉的雪猴、松本城與善光寺，看點數不盡。夏天避暑健行，冬天到白馬、野澤滑雪、泡雪見溫泉。信州蕎麥麵、野澤菜和蘋果是招牌。愛山的人，先來這裡。',
  21: '岐阜有白川鄉的合掌造和城下町飛驒高山。在老街吃飛驒牛握壽司、逛早市是經典玩法。下呂溫泉是日本三名泉之一。長良川鵜飼（5-10月）是延續1300年的夏日風物詩。雪中白川鄉的點燈，是冬天限定的犒賞。',
  22: '靜岡夾在富士山與駿河灣之間，是茶與山葵之縣。三保松原遠眺富士、日本平的茶田、伊豆的溫泉與海岸線都是看點。駿河灣的櫻花蝦、吻仔魚、鰻魚和靜岡關東煮讓餐桌豐盛。熱海、修善寺從東京坐新幹線轉眼即到。邊看富士山邊泡露天溫泉，無與倫比。',
  23: '愛知是名古屋美食的大本營：味噌豬排、鰻魚三吃、炸雞翅和獨特的早餐文化，個性全國屈指可數。金鯱的名古屋城、德川美術館、吉卜力公園等看點也多彩。三河灣的藝術小島佐久島人氣上升中。適合以城市漫步和吃遍美食為軸的旅行。',
  24: '三重是伊勢神宮之縣，日本人「一生一次伊勢參拜」的目的地，托福橫丁的邊走邊吃也是樂趣。夫婦岩的日出、保留海女文化的鳥羽與志摩、里亞斯海岸的英虞灣都值得一看。松阪牛、伊勢龍蝦、手捏壽司都是一流。凜冽冬晨的參拜尤其清爽。',
  25: '滋賀環抱日本第一大湖琵琶湖。湖中浮著鳥居的白鬚神社、國寶彥根城、比叡山延曆寺，水與歷史的景點一字排開。近江牛是日本最古老的和牛品牌。環湖騎行路線「琵琶一」是騎士的聖地。從京都只需10分鐘，就能遇見這份寧靜。',
  26: '京都，千年之都。伏見稻荷的千本鳥居、金閣寺、清水的舞台——名勝數之不盡。櫻花與紅葉美得出眾，人潮也隨之而來；清晨的竹林、夜晚的先斗町，錯峰而行才是行家走法。從湯豆腐到懷石、抹茶甜點，連飲食都風雅。',
  27: '大阪，「吃到破產」之城。道頓堀的霓虹和固力果招牌下，章魚燒、大阪燒、串炸一路吃過去才是王道。大阪城、通天閣、日本環球影城，玩樂場所也齊全。街頭親切熱絡的空氣日本第一。想要夜生活長、充滿歡笑與美食的旅行，就來這裡。',
  28: '兵庫擁有被稱為白鷺城的世界遺產姬路城。神戶異國情調的街區、六甲山的千萬美元夜景、城崎溫泉的外湯巡遊，陣容多彩。神戶牛、明石燒、灘之清酒不可錯過。有馬溫泉是豐臣秀吉鍾愛的日本最古老名湯之一。城市、城堡、溫泉一次滿足。',
  29: '奈良是大佛與鹿的古都。東大寺大佛殿、鹿會鞠躬的奈良公園、朱紅的春日大社是經典路線。稍走遠些，還有4月漫山櫻花的吉野山和日本最古老的道路「山之邊之道」。柿葉壽司和葛餅是名物。比京都人少，能遇見更古老的日本。',
  30: '和歌山是熊野古道與高野山的祈禱之縣。走過杉木參道，宿坊過夜，體驗精進料理和晨間誦經。那智瀑布與朱紅寶塔的同框美得屏息。白濱的沙灘與貓熊、勝浦的鮪魚也是亮點。適合喜歡健行、想讓身心歸位的人。',
  31: '鳥取擁有日本最大級的沙丘。可以騎駱駝、玩滑沙，再到旁邊的砂之美術館欣賞沙雕藝術。《鬼太郎》的水木茂之路、白壁土藏的倉吉也值得一逛。冬天的松葉蟹和二十世紀梨是名物。遊客之少全國屈指——這正是奢侈所在。',
  32: '島根是結緣之神出雲大社的故鄉。參拜傳說中眾神聚集的神社，再看宍道湖的夕陽是王道。世界遺產石見銀山、護城河遊船的松江城、庭園日本第一的足立美術館，深度景點雲集。出雲蕎麥麵和蜆湯是名物。神在月（舊曆10月）的參拜別具意義。',
  33: '「晴天之國」岡山。白壁垂柳的倉敷美觀地區、日本三名園的後樂園與烏城（岡山城）是招牌。這裡也是前往犬島、豐島藝術之旅的門戶。白桃、麝香葡萄、散壽司不負水果王國之名。少雨的氣候，讓這裡一年四季都少有失手。',
  34: '廣島擁有兩處世界遺產：原爆圓頂館與嚴島神社。宮島海上的大鳥居，漲潮退潮各有一番面貌。廣島燒、牡蠣、尾道拉麵，美食陣容同樣強大。騎行島波海道，用身體感受瀨戶內海的多島之美。這是一場直面歷史、被大海療癒的旅行。',
  35: '本州最西端的山口。錦帶橋的五連拱、被CNN評為「日本最美地方」之一的元乃隅神社紅色鳥居長陣、秋吉台的喀斯特台地，處處上鏡。下關的河豚是本場中的本場。在萩的城下町，可以追尋幕末志士的足跡。安靜而濃厚，是行家偏愛之縣。',
  36: '德島是阿波舞與鳴門漩渦之鄉。8月的阿波舞節，全城變成舞池。祖谷的藤蔓橋與深谷是日本三大秘境之一。鳴門海峽的漩渦，坐船或走玻璃地板步道都能看。德島拉麵、酢橘、鳴門鯛是名物。夏日祭典加秘境漫步，是這裡的兩大主軸。',
  37: '「烏龍麵縣」香川。從早上就開始逐家品嘗製麵所的讚岐烏龍麵巡禮是名物。瀨戶內國際藝術祭的直島、豐島是世界聞名的藝術聖地。米其林三星的栗林公園、金刀比羅宮的785級石階也是看點。日本最小的縣，塞滿了美食與藝術。',
  38: '愛媛是道後溫泉之鄉。在被稱為《神隱少女》原型之一的道後溫泉本館泡湯，再穿浴衣逛商店街是經典玩法。現存12天守之一的松山城、島波海道的群島、宇和海的梯田海岸也是看點。鯛魚飯和蜜柑是本場之味。在文學之城松山，還能追尋正岡子規的足跡。',
  39: '高知是「最後的清流」四萬十川之縣。騎車過沉下橋、划獨木舟順流而下的旅行只此一家。8月的夜來祭、週日市集、桂濱的坂本龍馬像也是經典。稻草炙燒的鰹魚半敲燒，從香氣就與眾不同。柏島的海水透明度堪比沖繩。豪爽的美食與戲水，最適合夏天。',
  40: '福岡是屋台（路邊攤）之城。在中洲河畔的屋台，從豚骨拉麵吃到炒拉麵的夜晚是名物。太宰府天滿宮的梅花、糸島的海邊咖啡館、柳川的遊船，一日遊也很充實。牛雜鍋、明太子、烏龍麵——美食底蘊九州第一。機場到市區地鐵5分鐘的便利也是魅力。',
  41: '佐賀是有田燒、伊萬里燒的故鄉。漫步窯元小鎮，體驗拉坯、選購器皿。呼子的早市有透明的活魷魚刺身。懸崖上的祐德稻荷神社和秋天的熱氣球節（11月）也是看點。嬉野、武雄的溫泉同樣是名湯。這裡屬於熱愛器物與美食的人。',
  42: '長崎是坡道與教堂的港城。哥拉巴園、大浦天主堂、稻佐山的「世界新三大夜景」是經典。乘軍艦島巡航，可以登上廢墟之島。強棒麵、皿烏龍麵、蜂蜜蛋糕——鎖國時代唯一窗口孕育的和華蘭美食也是魅力。乘路面電車遊走的異國情調，日本別處找不到。',
  43: '熊本是阿蘇大破火山口與熊本城之縣。馬群奔跑的草千里、雲海之上的大觀峰，大尺度的風景接連不斷。復建中的熊本城、清澈的白川水源也值得一看。馬肉刺身、紅牛蓋飯、芥末蓮藕是名物。再加上黑川溫泉的露天巡湯，自然、城堡、溫泉一次到位。',
  44: '大分是源泉數與湧出量均為日本第一的「溫泉縣」。在別府巡遊「地獄」、體驗砂浴；在由布院看金鱗湖的晨霧、逛精緻的溫泉街。炸雞天婦羅、關鰺關鯖、糰子汁是名物。由布院的紅葉和雪見露天的冬天尤其有風情。若溫泉是旅行的目的，這裡就是頂點。',
  45: '宮崎是神話與南國之縣。在天孫降臨之地高千穗峽划船仰望真名井瀑布，體驗獨一無二。鬼之洗衣板鋪展的青島、都井岬的野生馬、日南海岸兜風都令人暢快。雞南蠻、地雞炭火燒、芒果是名物。冬天也溫暖，一年四季都能衝浪。',
  46: '鹿兒島是櫻島噴煙的薩摩之國。一邊眺望錦江灣對岸的活火山，一邊在指宿埋進天然砂蒸溫泉，這體驗僅此一處。世界遺產屋久島的繩文杉、奄美的大海都在範圍內，自然尺度非凡。黑豚涮涮鍋、薩摩炸魚餅、芋燒酎是名物。維新歷史濃厚，看點無窮。',
  47: '沖繩保留著琉球王國的面影，擁有世界屈指的大海。在首里城和齋場御嶽感受琉球的祈禱，再到慶良間、宮古、石垣的海域浮潛與潛水。沖繩麵、苦瓜炒什錦、泡盛，飲食文化自成一派。海的最佳季節是5-10月，冬天也有20度上下的溫暖。這是日本之中的另一個國度。',
};

const BY_LOCALE: Record<Locale, Record<number, string>> = {
  en: EN,
  ja: JA,
  ko: KO,
  'zh-Hans': ZH_HANS,
  'zh-Hant': ZH_HANT,
};

/** その県の紹介文。無い言語は英語へ落とす（キーの欠けで空文を出さない） */
export function prefectureDescription(code: number, locale: Locale): string {
  return BY_LOCALE[locale]?.[code] ?? EN[code] ?? '';
}
